Models/Cliente.cs
namespace clientes_front.Models
{
    public class Cliente
    {

        public int Id { get; set; }

        public string Nombre { get; set; }

        public string ApellidoPaterno { get; set; }

        public string ApellidoMaterno { get; set; }

        public int Edad { get; set; }

        public DateTime FechaNacimiento { get; set; }

        public string Genero { get; set; }

        public string EstadoCivil { get; set; }

        public string RFC { get; set; }

        public string Direccion { get; set; }

        public string Email { get; set; }

        public string Telefono { get; set; }

        public string Puesto { get; set; }

        public string Estatus { get; set; }

        public DateTime FechaAlta { get; set; }

        public DateTime? FechaBaja { get; set; }
    }
}

Models/ClienteFiltroDTO.cs
namespace clientes_front.Models
{
    public class ClienteFiltroDTO
    {
        public int Id { get; set; }
        public string Nombre { get; set; }

        public string RFC { get; set; }

        public string Estatus { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace clientes_front.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/MiltiModel.cs
namespace clientes_front.Models
{
    public class MiltiModel
    {
       public IEnumerable<Cliente> ClientesList { get; set; }

       public ClienteFiltroDTO ClienteFiltroDTO { get; set; }
    }
}

Controllers/ClienteController.cs
using clientes_front.Models;
using Microsoft.AspNetCore.Mvc;

namespace clientes_front.Controllers
{
    public class ClienteController : Controller
    {
        private string path = "http://localhost:5285/api/";
       
        public async Task<IActionResult> Guardar(Cliente cliente)
        {
            using (var client = new HttpClient())
            {
                DateTime localDate = DateTime.Now;
                cliente.FechaAlta = localDate;
                cliente.Estatus = "Activo";
                int edad = DateTime.Today.AddTicks(-cliente.FechaNacimiento.Ticks).Year - 1;
                cliente.Edad = edad;
                client.BaseAddress = new Uri(path);
                var result = await client.PostAsJsonAsync("clientes", cliente);
                string resultContent = await result.Content.ReadAsStringAsync();

                if (result.StatusCode== System.Net.HttpStatusCode.BadRequest)
                {
                    return View(cliente);
                }
                else
                {
                    return RedirectToAction("Lista");
                }
            }
          
        }

        public IActionResult Lista()
        {
            IEnumerable<Cliente> clientes = null;

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(path);
                var responseTask = client.GetAsync("clientes");
                responseTask.Wait();

                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<IList<Cliente>>();
                    readTask.Wait();
                    clientes = readTask.Result;
                }
                else 
                {                  
                    clientes = Enumerable.Empty<Cliente>();
                    ModelState.AddModelError(string.Empty, "Error al comunicarse con el servidor, favor de comunicarse con el proveedor.");
                }
            }

            MiltiModel miltiModel = new MiltiModel();
            miltiModel.ClientesList = clientes;
            return View(miltiModel);
        }

  
        public IActionResult Editar(int  id)
        {
            Cliente clientes = null;

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(path);
                var responseTask = client.GetAsync("clientes/"+id);
                responseTask.Wait();

                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<Cliente>();
                    readTask.Wait();
                    clientes = readTask.Result;
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Error al comunicarse con el servidor, favor de comunicarse con el proveedor.");
                }
            }
            return View(clientes);
        }

        [HttpPost]
        public async Task<IActionResult> Editar(Cliente cliente)
        {

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(path);
                if (cliente.FechaBaja != null)
                {
                    cliente.Estatus = "Inactivo";
                }
                var result = await client.PutAsJsonAsync("clientes", cliente);
                string resultContent = await result.Content.ReadAsStringAsync();
            }
            return RedirectToAction("Lista");
        }

        [HttpPost()]
        public async Task<IActionResult> EliminarAsync(int id)
        {

            Cliente clientes = null;

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(path);
                var responseTask = client.GetAsync("clientes/" + id);
                responseTask.Wait();

                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<Cliente>();
                    readTask.Wait();
                    clientes = readTask.Result;
                   
                    DateTime localDate = DateTime.Now;
                    clientes.FechaBaja = localDate;
                    clientes.Estatus = "Inactivo";
                    var resultEdit = await client.PutAsJsonAsync("clientes", clientes);
                    string resultContentEdit = await result.Content.ReadAsStringAsync();

                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Error al comunicarse con el servidor, favor de comunicarse con el proveedor.");
                }
            }
             
           
            return RedirectToAction("Lista");
        }

        [HttpPost]
        public IActionResult Lista(ClienteFiltroDTO clienteFiltroDTO)
        {
            IEnumerable<Cliente> clientes = null;

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(path);
                var responseTask = client.PostAsJsonAsync("clientes/getFilter",clienteFiltroDTO);
                responseTask.Wait();

                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<IList<Cliente>>();
                    readTask.Wait();
                    clientes = readTask.Result;
                }
                else
                {
                    clientes = Enumerable.Empty<Cliente>();
                    ModelState.AddModelError(string.Empty, "Error al comunicarse con el servidor, favor de comunicarse con el proveedor.");
                }
            }

            MiltiModel miltiModel = new MiltiModel();
            miltiModel.ClientesList = clientes;
            return View(miltiModel);
        }
    }
}

Views/Cliente/Editar.cshtml
@model Cliente
@{
    ViewData["Title"] = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="card">
  <div class="card-header">
   Editar Cliente
  </div>
  <div class="card-body">
   <form asp-action="Editar" asp-controller="Cliente" method="post">
   <input type="hidden" class="form-control" asp-for="Id">
   <input type="hidden" class="form-control" asp-for="Nombre">
   <input type="hidden" class="form-control" asp-for="ApellidoPaterno">
   <input type="hidden" class="form-control" asp-for="ApellidoMaterno">
   <input type="hidden" class="form-control" asp-for="Edad">
   <input type="hidden" class="form-control" asp-for="FechaNacimiento">
   <input type="hidden" class="form-control" asp-for="Genero">
   <input type="hidden" class="form-control" asp-for="RFC">
   <input type="hidden" class="form-control" asp-for="Estatus">
   <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Correo Electronico</label>
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" asp-for="Email"
    title="Formato incorrecto.Ejemplo algo@dominio.com">
  </div>
   <div class="mb-3">
    <label  class="form-label">Telefono</label>
    <input type="tel" class="form-control" asp-for="Telefono"  pattern="[0-9]{10}" 
       title="Formato incorrecto.Ejemplo 0000000000">
  </div>
  <div class="mb-3">
    <label  class="form-label">Puesto</label>
    <select class="form-select" aria-label="Default select example" asp-for="Puesto">
      <option value="1">Administrador</option>
      <option value="2">Sistemas</option>
      <option value="3">QA</option> 
    </select>
  </div>
  <div class="mb-3">
    <label  class="form-label">Fecha Baja</label>
    <input type="date" class="form-control" asp-for="FechaBaja">
  </div>
  <div class="mb-3">
 <label  class="form-label">Estado Civil</label>
    <select class="form-select" aria-label="Default select example" asp-for="EstadoCivil">
      <option value="Casado">Casado</option>
      <option value="Divorciado">Divorciado</option>
       <option value="Soltero">Soltero</option>
       <option value="Concuvinato">Concuvinato</option>
         <option value="Otro">Otro</option>
    </select>
  </div>
  <div class="mb-3">
    <label  class="form-label">Direccion</label>
    <input type="text" class="form-control" asp-for="Direccion" onkeyup="this.value = this.value.toUpperCase();">
  </div>

  <div class="card-body">
      <button type="submit" class="btn btn-primary">Actualizar</button>
      <a asp-action="Lista" asp-controller="Cliente" class="btn btn-secondary">Cancelar</a>
      
  </div>
</form>
</div>

Views/Cliente/Guardar.cshtml
@model Cliente
@{
    ViewData["Title"] = "Guardar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
 
<div class="card">
  <div class="card-header">
    Crear usuario
  </div>
  <div class="card-body">
   <form asp-action="Guardar" asp-controller="Cliente">
  <div class="mb-3">
    <label  class="form-label">Nombre</label>
    <input type="text" class="form-control" asp-for="Nombre"  onkeyup="this.value = this.value.toUpperCase();">
  </div>
  <div class="mb-3">
    <label  class="form-label">Apellido Paterno</label>
    <input type="text" class="form-control" asp-for="ApellidoPaterno" onkeyup="this.value = this.value.toUpperCase();">
  </div>
  <div class="mb-3">
    <label  class="form-label">Apellido Materno</label>
    <input type="text" class="form-control" asp-for="ApellidoMaterno" onkeyup="this.value = this.value.toUpperCase();">
  </div>
  <div class="mb-3">
    <label  class="form-label">Fecha Nacimiento</label>
     <input type="date" class="form-control" asp-for="FechaNacimiento">
  </div>
  <div class="mb-3">
       <label  class="form-label">Genero</label>
    <select class="form-select" aria-label="Default select example" asp-for="Genero">
      <option value="M">Masculino</option>
      <option value="F">Femenino</option>
       <option value="O">Otro</option>
    </select>
  </div>
  <div class="mb-3">
   <label  class="form-label">Estado Civil</label>
    <select class="form-select" aria-label="Default select example" asp-for="EstadoCivil">
      <option value="Casado">Casado</option>
      <option value="Divorciado">Divorciado</option>
       <option value="Soltero">Soltero</option>
       <option value="Concuvinato">Concuvinato</option>
         <option value="Otro">Otro</option>
    </select>
  </div>
  <div class="mb-3">
    <label  class="form-label">RFC</label>
    <input type="text" class="form-control" asp-for="RFC" pattern="^[A-Z&Ñ]{3,4}[0-9]{2}(0[1-9]|1[012])(0[1-9]|[12][0-9]|3[01])[A-Z0-9]{2}[0-9A]$" onkeyup="this.value = this.value.toUpperCase();">
  </div>
  <div class="mb-3">
    <label  class="form-label">Direccion</label>
    <input type="text" class="form-control" asp-for="Direccion" onkeyup="this.value = this.value.toUpperCase();">
  </div>
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Correo Electronico</label>
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" asp-for="Email"
        title="Formato incorrecto.Ejemplo algo@dominio.com">
  </div>
  <div class="mb-3">
    <label  class="form-label">Telefono</label>
    <input type="tel" class="form-control" asp-for="Telefono"  pattern="[0-9]{10}" 
       title="Formato incorrecto.Ejemplo 0000000000">
  </div>
  <div class="mb-3">
    <label  class="form-label">Puesto</label>
    <select class="form-select" aria-label="Default select example" asp-for="Puesto">
      <option value="1">Administrador</option>
      <option value="2">Sistemas</option>
      <option value="3">QA</option> 
    </select>
  </div>
  <div class="card-body">
      <button type="submit" class="btn btn-primary">Guardar</button>
      <a asp-action="Lista" asp-controller="Cliente" class="btn btn-secondary">Cancelar</a>
  </div>
</form>
</div>

Views/Cliente/Lista.cshtml
@model MiltiModel

@{
    ViewData["Title"] = "Lista";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
 
 <form asp-action="Lista" asp-controller="Cliente" method="post">
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Filtros</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="mb-3">
          <div class="modal-body">
          <div class="mb-3">
              <label  class="form-label">Nombre</label>
              <input type="text" class="form-control" asp-for="@Model.ClienteFiltroDTO.Nombre">
          </div>
          <div class="mb-3">
              <label  class="form-label">RFC</label>
              <input type="text" class="form-control" asp-for="@Model.ClienteFiltroDTO.RFC"  pattern="^[A-Z&Ñ]{3,4}[0-9]{2}(0[1-9]|1[012])(0[1-9]|[12][0-9]|3[01])[A-Z0-9]{2}[0-9A]$">
          </div>
 <div class="mb-3">
       <label  class="form-label">Estatus</label>
    <select class="form-select" aria-label="Default select example" asp-for="@Model.ClienteFiltroDTO.Estatus">
      <option value="Activo">Activo</option>
      <option value="Inactivo">Inactivo</option>
    </select>
  </div>
         </div>
      </div>
      <div class="modal-footer">
           <button type="submit"  class="btn btn-primary" data-bs-dismiss="modal">Buscar</button>
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
       
      </div>
     
    </div>
  </div>
</div>
</form>

 <form asp-action="Eliminar" asp-controller="Cliente" method="post">
<div class="card">
  <div class="card-header">
   Listado de Clientes
  </div>
  <div class="card-body">
    <a asp-action="Guardar" asp-controller="Cliente" class="btn btn-success">Crear</a>
    <a asp-action="Lista" asp-controller="Cliente" class="btn btn-success">Actualizar</a>
    <a asp-action="Filtrar" asp-controller="Cliente" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#exampleModal">Buscar</a>
    <hr />
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Correo electronico</th>
                <th>Puesto</th>
                <th>RFC</th>
                <th>Fecha Alta</th>
                <th>Acciones</th>
            </tr>
         </thead>
         <tbody>
             @foreach (var item in @Model.ClientesList)
             {
                 <tr>
                     <td>@item.Nombre @item.ApellidoPaterno @item.ApellidoMaterno </td>
                     <td>@item.Email</td>                    
                     <td>@(item.Puesto =="1" ? "Administrador" : item.Puesto =="2"? "Sistemas": "QA")</td>
                     <td>@item.RFC</td>
                     <td>@item.FechaAlta.Date.ToString("dd/MM/yyyy")</td>
                     <td>
                          <a asp-action="Editar" asp-controller="Cliente" class="btn btn-primary btn-sm" asp-route-id="@item.Id">Editar</a>
                          <button asp-action="Eliminar" asp-route-id="@item.Id" class="btn btn-primary btn-sm" onclick="return confirm('¿Estas seguro que deceas eliminar el usuario?')">Eliminar</button>
                     </td>
                 </tr>
             }
         </tbody>
    </table>
</div>
</form>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - clientes_front</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/clientes_front.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">

        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>